apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.frontend.deploymentName }}
spec:
  selector:
    app: {{ .Values.frontend.deploymentName }}
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.container.port }}
      protocol: TCP
      name: http
