apiVersion: v1
kind: Service
metadata:
   name: {{ .Values.postgres.deploymentName }}
   namespace: toducze-test
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.container.port }}
  selector:
    app: {{ .Values.postgres.deploymentName }}