apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.deploymentName }}
  namespace: {{ .Values.namespace }}
spec:
    replicas: {{ .Values.postgres.replicaCount }}
    selector:
      matchLabels:
        app: {{ .Values.postgres.deploymentName }}
    template:
      metadata:
        labels:
          app: {{ .Values.postgres.deploymentName }}
      spec:
        containers:
          - name: {{ .Values.postgres.deploymentName }}
            image: {{ .Values.postgres.container.image.repository }}
            imagePullPolicy: {{ .Values.postgres.container.image.pullPolicy }}
            ports:
              - containerPort: {{ .Values.postgres.container.port }}
            envFrom:
              - configMapRef:
                  name: {{ .Values.configMap.postgres.name }}
            volumeMounts:
               - mountPath: /var/lib/postgresql/data
                 name: postgredb
        volumes:
          - name: postgredb
            persistentVolumeClaim:
              claimName: postgres-pv-claim